name: take_app_rest
# name: hotel_app
description: HotelApp - Tu estadia ideal, siempre.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0                      # Para llamadas HTTP a la API
  shared_preferences: ^2.2.2        # Para guardar el token JWT localmente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true